<?php
require_once __DIR__ . '/lib/tickets.php';
verify_csrf(); require_approved_client();
if ($_SERVER['REQUEST_METHOD'] !== 'POST' || !rate_limit('ticket', 10, 3600)) { flash('error', 'Não foi possível abrir o chamado agora.'); redirect('/cliente.php'); }
$allowedSystems = ['Instalação Elétrica', 'Instalação Hidráulica', 'Sistema de Combate a Incêndio', 'Outro']; $allowedPriorities = ['Baixa', 'Média', 'Urgente'];
$input = ['development' => trim($_POST['development'] ?? ''), 'unit' => trim($_POST['unit'] ?? ''), 'system' => $_POST['system'] ?? '', 'priority' => $_POST['priority'] ?? '', 'description' => trim($_POST['description'] ?? '')];
$name = trim($_POST['name'] ?? ''); $email = filter_var(trim($_POST['email'] ?? ''), FILTER_VALIDATE_EMAIL); $phone = trim($_POST['phone'] ?? '');
if ($name === '' || !$email || $phone === '' || $input['development'] === '' || !in_array($input['system'], $allowedSystems, true) || !in_array($input['priority'], $allowedPriorities, true) || mb_strlen($input['description']) < 15 || mb_strlen($input['description']) > 4000) { flash('error', 'Revise os dados do chamado.'); redirect('/cliente.php'); }
$client = current_user(); $profile = find_client($client['id']); $name = $client['name']; $email = $client['email']; $phone = $profile['phone'] ?? ''; try { $ticket = create_ticket($input, $client); record_audit('ticket_created', $client['id'], $ticket['id'], ['number' => $ticket['number']]); $safe = fn($value) => htmlspecialchars((string) $value, ENT_QUOTES, 'UTF-8'); send_administrative_notification('Novo chamado ' . $ticket['number'] . ' — Baken', '<p><strong>' . $safe($ticket['number']) . '</strong></p><p>Cliente: ' . $safe($name) . '<br>E-mail: ' . $safe($email) . '<br>Telefone: ' . $safe($phone) . '<br>Empreendimento: ' . $safe($ticket['development']) . '<br>Sistema: ' . $safe($ticket['system']) . '<br>Prioridade: ' . $safe($ticket['priority']) . '</p><p>' . nl2br($safe($ticket['description'])) . '</p>', $email, $name); send_site_mail($client['email'], 'Recebemos seu chamado ' . $ticket['number'], '<p>Recebemos seu chamado de assistência técnica. Número: <strong>' . $safe($ticket['number']) . '</strong>.</p>'); flash('success', 'Chamado ' . $ticket['number'] . ' aberto com sucesso.'); } catch (Throwable $e) { error_log($e->getMessage()); flash('error', 'Não foi possível registrar o chamado.'); } redirect('/cliente.php');
