<?php
require_once __DIR__ . '/lib/layout.php';
require_once __DIR__ . '/lib/tickets.php';
$user = current_user();
if (is_admin()) redirect('/admin/index.php');
page_start('Portal do Cliente', false);
?>
<?php if (!$user): ?>
  <h1>Assistência Técnica Pós-Obra</h1>
  <div class="card"><h2>Acesso restrito</h2><p>Para abrir um chamado, crie sua conta e aguarde a aprovação da Baken.</p><p><a class="btn" href="/portal-cliente/cadastro">Criar cadastro</a> <a class="btn alt" href="/portal-cliente/entrar">Entrar</a></p></div>
<?php elseif (!is_approved_client()): ?>
  <h1>Assistência Técnica Pós-Obra</h1>
  <div class="card"><h2>Cadastro em análise</h2><p>Seu cadastro está <strong><?= htmlspecialchars($user['status'] === 'pending' ? 'pendente de aprovação' : $user['status']) ?></strong>. Você receberá uma notificação após a análise.</p></div>
<?php else: $profile = find_client($user['id']); $tickets = tickets_for_client($user['id']); ?>
  <section class="ticket-portal-header"><div class="ticket-portal-badge">Portal do Cliente</div><h1>Assistência Técnica Pós-Obra</h1><p>Abra um chamado e nossa equipe técnica entrará em contato em até 1 dia útil.</p></section>
  <nav class="ticket-tabs" role="tablist" aria-label="Área de assistência"><button id="ticket-tab-novo" type="button" role="tab" aria-selected="true" aria-controls="ticket-novo" data-ticket-tab="ticket-novo">Novo chamado</button><button id="ticket-tab-historico" type="button" role="tab" aria-selected="false" aria-controls="ticket-historico" data-ticket-tab="ticket-historico">Meus chamados <span><?= count($tickets) ?></span></button></nav>
  <section id="ticket-novo" class="ticket-panel" role="tabpanel" aria-labelledby="ticket-tab-novo">
    <div class="ticket-portal-card"><div class="ticket-portal-card__head"><div class="ticket-portal-card__icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/><line x1="16" y1="13" x2="8" y2="13"/><line x1="16" y1="17" x2="8" y2="17"/></svg></div><div><strong>Novo Chamado</strong><span>Assistência técnica e manutenção</span></div></div><div class="ticket-portal-card__body">
      <form method="post" action="/portal-cliente/chamados"><input type="hidden" name="csrf" value="<?= htmlspecialchars(csrf_token()) ?>">
        <div class="form-row"><div class="field"><label for="ticket-name">Nome completo <b>*</b></label><input id="ticket-name" name="name" required maxlength="120" value="<?= htmlspecialchars($user['name']) ?>"></div><div class="field"><label for="ticket-phone">Telefone <b>*</b></label><input id="ticket-phone" type="tel" name="phone" required maxlength="20" placeholder="(62) 9 9999-9999" value="<?= htmlspecialchars($profile['phone'] ?? '') ?>"></div></div>
        <div class="field"><label for="ticket-email">E-mail <b>*</b></label><input id="ticket-email" type="email" name="email" required maxlength="254" value="<?= htmlspecialchars($user['email']) ?>"></div>
        <div class="form-row"><div class="field"><label for="ticket-development">Empreendimento / Obra <b>*</b></label><input id="ticket-development" name="development" required maxlength="120" placeholder="Nome do condomínio ou obra" value="<?= htmlspecialchars($profile['development'] ?? '') ?>"></div><div class="field"><label for="ticket-unit">Unidade / Bloco</label><input id="ticket-unit" name="unit" maxlength="80" placeholder="Ex: Apto 402, Bloco B" value="<?= htmlspecialchars($profile['unit'] ?? '') ?>"></div></div>
        <div class="field"><label for="ticket-system">Sistema com problema <b>*</b></label><select id="ticket-system" name="system" required><option value="" selected disabled>Selecione o sistema</option><option value="Instalação Elétrica">Instalação Elétrica</option><option value="Instalação Hidráulica">Instalação Hidráulica</option><option value="Sistema de Combate a Incêndio">Sistema de Combate a Incêndio</option><option value="Outro">Outro</option></select></div>
        <fieldset class="ticket-priority"><legend>Prioridade do chamado <b>*</b></legend><div><input type="radio" name="priority" id="ticket-low" value="Baixa"><label for="ticket-low"><span>🟢</span>Baixa</label></div><div><input type="radio" name="priority" id="ticket-medium" value="Média" checked><label for="ticket-medium"><span>🟡</span>Média</label></div><div><input type="radio" name="priority" id="ticket-urgent" value="Urgente"><label for="ticket-urgent"><span>🔴</span>Urgente</label></div></fieldset>
        <div class="field"><label for="ticket-description">Descrição do problema <b>*</b></label><textarea id="ticket-description" name="description" required minlength="15" maxlength="4000" placeholder="Descreva com detalhes o problema: quando começou, sintomas observados, se houve algum evento antes..."></textarea></div><div class="ticket-divider"></div><button class="ticket-submit">Abrir chamado <span>↗</span></button><p class="ticket-privacy">O chamado será enviado para nossa equipe técnica por e-mail. Retorno em até 1 dia útil.</p>
      </form>
    </div></div>
    <aside class="ticket-note"><strong>Emergência?</strong><span>Para situações urgentes como vazamento ativo ou falha no sistema de incêndio, entre em contato direto pelo telefone <a href="tel:+5562999509148">(62) 99950-9148</a>.</span></aside><form class="client-unsubscribe" method="post" action="/portal-cliente/descadastro"><input type="hidden" name="csrf" value="<?= htmlspecialchars(csrf_token()) ?>"><button type="submit" data-confirm="Deseja solicitar o descadastro? Seu acesso será bloqueado imediatamente e a Baken analisará a exclusão ou anonimização dos seus dados." data-confirm-title="Solicitar descadastro?" data-confirm-action="Solicitar descadastro">Solicitar descadastro</button></form>
  </section>
  <section id="ticket-historico" class="ticket-panel" role="tabpanel" aria-labelledby="ticket-tab-historico" hidden><div class="ticket-portal-card"><div class="ticket-portal-card__head"><div class="ticket-portal-card__icon">✓</div><div><strong>Meus chamados</strong><span>Acompanhe suas solicitações de assistência</span></div></div><div class="ticket-portal-card__body"><?php if (!$tickets): ?><p class="muted">Nenhum chamado registrado.</p><?php else: ?><div class="data-table__scroll"><table class="table"><thead><tr><th>Número</th><th>Sistema</th><th>Status</th><th>Data</th></tr></thead><tbody><?php foreach (array_reverse($tickets) as $ticket): ?><tr><td><strong><?= htmlspecialchars($ticket['number']) ?></strong></td><td><?= htmlspecialchars($ticket['system']) ?></td><td><?= htmlspecialchars($ticket['status']) ?></td><td><?= htmlspecialchars(date('d/m/Y H:i', strtotime($ticket['created_at']))) ?></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></div></div></section>
<?php endif; page_end(); ?>
