<?php
require_once __DIR__ . '/lib/accounts.php';
verify_csrf();
if ($_SERVER['REQUEST_METHOD'] !== 'POST') redirect('/cadastro.php');
if (!rate_limit('register', 5, 3600) || !empty($_POST['website'] ?? '')) { flash('success', 'Cadastro realizado com sucesso. Sua solicitação de acesso está em análise e você receberá um e-mail assim que ela for liberada.'); redirect('/login.php'); }
$data = ['name' => trim($_POST['name'] ?? ''), 'email' => trim($_POST['email'] ?? ''), 'phone' => trim($_POST['phone'] ?? ''), 'development' => trim($_POST['development'] ?? ''), 'unit' => '', 'password' => $_POST['password'] ?? ''];
$passwordConfirm = $_POST['password_confirm'] ?? '';
if (in_array('', [$data['name'], $data['email'], $data['phone'], $data['development'], $data['password']], true) || !filter_var($data['email'], FILTER_VALIDATE_EMAIL) || strlen($data['password']) < 9 || !preg_match('/[A-Za-z]/', $data['password']) || !preg_match('/\d/', $data['password']) || !is_string($passwordConfirm) || !hash_equals($data['password'], $passwordConfirm) || empty($_POST['privacy'])) { keep_old_input(['name' => $data['name'], 'email' => $data['email'], 'phone' => $data['phone'], 'development' => $data['development'], 'privacy' => !empty($_POST['privacy'])]); flash('error', 'Revise os campos obrigatórios e confirme a senha corretamente.'); redirect('/cadastro.php'); }
try { $user = create_client($data); record_audit('registration_created', $user['id'], $user['id']); $adminUrl = app_url('/admin/entrar'); $email = '<p>Olá,</p><p>Há uma nova solicitação de acesso ao Portal do Cliente que aguarda sua análise.</p><table role="presentation" style="border-collapse:collapse;width:100%;max-width:560px;background:#f6f7f8"><tr><td style="padding:16px"><strong>Cliente:</strong> ' . htmlspecialchars($user['name']) . '<br><strong>E-mail:</strong> ' . htmlspecialchars($user['email']) . '<br><strong>Telefone:</strong> ' . htmlspecialchars($user['phone']) . '<br><strong>Empreendimento / obra:</strong> ' . htmlspecialchars($user['development']) . '</td></tr></table><p>Entre na área administrativa para aprovar ou recusar o cadastro com segurança.</p>' . email_button($adminUrl, 'Acessar área administrativa') . '<p style="color:#5f6470;font-size:14px">A aprovação exige seu login administrativo.</p>'; send_administrative_notification('Novo cadastro pendente — Baken', $email, $user['email'], $user['name']); } catch (DomainException) { /* resposta neutra */ } catch (Throwable $e) { error_log($e->getMessage()); flash('error', 'Não foi possível registrar a solicitação agora.'); redirect('/cadastro.php'); }
flash('success', 'Cadastro realizado com sucesso. Sua solicitação de acesso está em análise e você receberá um e-mail assim que ela for liberada.'); redirect('/login.php');
